version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  weather-api:
    build: .
    container_name: weather-api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/
  weather-bot:
    build: .
    container_name: weather-bot
    depends_on:
      - mongodb
    command: python weather_tg_bot.py
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/

volumes:
  mongo_data: